#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ngEPL_Android.Resource", IsApplication=true)]

namespace ngEPL_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fondo_content_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fondo_content_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fondo_degradado2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fondo_degradado3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fondo_item_permiso = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int imvIcon = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int lvBlock_List = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int lvCanvas = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_permission = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
